remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
title: Woojin's Adventure
description: Woojin's personal homepage
show_downloads: false
github:
- is_project_page: false
- is_user_page: true